import Vue from "vue";
import AppButton from "@/components/ui/AppButton";
import AppCard from "@/components/ui/AppCard";
import AppCheckbox from "@/components/ui/AppCheckbox";
import AppDivider from "@/components/ui/AppDivider";
import AppHeader from "@/components/ui/AppHeader";
import AppLabel from "@/components/ui/AppLabel";
import AppModal from "@/components/ui/AppModal";
import AppRadio from "@/components/ui/AppRadio";
import AppSelect from "@/components/ui/AppSelect";
import AppSidebar from "@/components/ui/AppSidebar";
import AppTab from "@/components/ui/AppTab";
import AppTabs from "@/components/ui/AppTabs";
import AppTag from "@/components/ui/AppTag";
import AppTagInput from "@/components/ui/AppTagInput";
import AppTextarea from "@/components/ui/AppTextarea";
import AppTextField from "@/components/ui/AppTextField";

Vue.component("app-button", AppButton);
Vue.component("app-card", AppCard);
Vue.component("app-checkbox", AppCheckbox);
Vue.component("app-divider", AppDivider);
Vue.component("app-header", AppHeader);
Vue.component("app-label", AppLabel);
Vue.component("app-modal", AppModal);
Vue.component("app-radio", AppRadio);
Vue.component("app-select", AppSelect);
Vue.component("app-sidebar", AppSidebar);
Vue.component("app-tab", AppTab);
Vue.component("app-tabs", AppTabs);
Vue.component("app-tag", AppTag);
Vue.component("app-tag-input", AppTagInput);
Vue.component("app-textarea", AppTextarea);
Vue.component("app-text-field", AppTextField);
